name: Build specific image

on:
  repository_dispatch:
    types: [build-image]
  workflow_dispatch:
    inputs:
      target:
        description: Target image subdirectory to build
        required: true
        type: string
      variant:
        description: Image variant to build
        required: false
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: report-inputs
        name: Report inputs
        run: |
          export TARGET="${{ github.event.inputs.target || github.event.client_payload.target }}"
          export VARIANT="${{ github.event.inputs.variant || github.event.client_payload.variant }}"
          echo "target=${TARGET}" >> $GITHUB_OUTPUT
          ./images/${TARGET}/init

      - name: Ensure inputs
        run: |
          if [ -z "${{ steps.report-inputs.outputs.target }}" ]; then
            echo "Missing target input"
            exit 1
          fi
          if [ -z "${{ steps.report-inputs.outputs.image }}" ]; then
            echo "Missing image input"
            exit 1
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ steps.report-inputs.outputs.image }}
          imageTag: ${{ steps.report-inputs.outputs.variant }}
          subFolder: images/${{ steps.report-inputs.outputs.target }}
          env: |
            VARIANT=${{ steps.report-inputs.outputs.variant }}
          push: always
